package symdb.service;

public class Contants {
	
static final String clmName="MANAGEDSYSTEM_ID,OPERATINGSYSTEM,OSVERSION,OSSERVICEPACK,LOCATION,SYSFUNCTION,SYSTEMTYPE,OVERALLHEALTH,SYSTEMHEALTH,HARDWAREHEALTH,NETWORKHEALTH,STORAGEHEALTH,SOFTWAREHEALTH,AGENTVERSION,"
		+ "NAME,IPADDRESS,NUMERICIPADDRESS,WOLIPADDRESS,WOLIPMASK,WOLMACADDRESS,LASTUPDATETS,ASSETNUMBER,ASSETVALUE,ASSETDATE,OWNER,MODEL,MANUFACTURER,NUMPROCESSORS,PROCESSORMODEL,BOARDMODEL,BOARDMFR,"
		+ "SENSORCHIPS,BIOSREVISION,PHYSICALMEMORYSIZE,PHYSICALMEMORYUSE,VIRTUALMEMORYSIZE,VIRTUALMEMORYUSE,DISPLAYMODEL,DISPLAYMEMORY,MONITORNAME,MONITORSERIAL,INUPDATE,DOMAIN,BOARDSERIAL,BIOSMANUFACTURER,"
		+ "BIOSRELEASEDATE,SMBIOSREVISION,PROCMFR,CPUCLOCKSPEED,MAXSUPPORTEDMEMORY,MEMORYSLOTS,LASTPOWEREVENT,LASTPOWEREVENTTS,ENCLOSUREASSETTAG,ENCLOSURESERIALNUMBER,SUPPORTSBIOSMGMT,SUPPORTSDASH,AGENT_KEYS,ACTIVE,ACCEPTED";
 
static final String Insert="INSERT INTO SYAM.MANAGEDSYSTEMS VALUES (";

}
